
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: deploy/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: deploy/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
